CREATE TYPE project_phase AS ENUM ('PLANNING', 'DEVELOPMENT', 'TESTING', 'DONE');
CREATE TYPE task_status AS ENUM ('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE');
CREATE TYPE qa_status AS ENUM ('PENDING', 'PASSED', 'FAILED');
CREATE TYPE access_level AS ENUM ('PM', 'MEMBER');